title: Tom Croucher aka sh1mmer
description: Programmer Musings
url: "https://sh1mmer.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"

# Collections
collections:
  posts:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
